# Generated by Django 3.1.7 on 2021-03-01 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Customer ID')),
                ('first_name', models.TextField(verbose_name='First Name')),
                ('last_name', models.TextField(verbose_name='Last Name')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='CustomProduct',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Product ID')),
                ('product_name', models.TextField(verbose_name='Product Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'CustomProduct',
                'verbose_name_plural': 'CustomProducts',
                'db_table': 'custom_products',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('email_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Email ID')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email Address')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'db_table': 'emails',
            },
        ),
        migrations.CreateModel(
            name='NonCustomProduct',
            fields=[
                ('p_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='P ID')),
                ('product_name', models.TextField(verbose_name='Product Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'NonCustomProduct',
                'verbose_name_plural': 'NonCustomProducts',
                'db_table': 'non_custom_products',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Order ID')),
                ('order_number', models.TextField(verbose_name='Order Number')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('status_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Status ID')),
                ('paid', models.BooleanField(default=False, verbose_name='Paid')),
            ],
            options={
                'verbose_name': 'OrderStatus',
                'verbose_name_plural': 'OrderStatuses',
                'db_table': 'order_status',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='OrderItem ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Order')),
                ('p', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.noncustomproduct', verbose_name='NonCustomProduct')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.customproduct', verbose_name='CustomProduct')),
            ],
            options={
                'verbose_name': 'OrderItem',
                'verbose_name_plural': 'OrderItems',
                'db_table': 'order_items',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderstatus', verbose_name='OrderStatus'),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.email', verbose_name='Email'),
        ),
    ]
